/// <reference types="vite/client" />

export const API = {
  // Same-origin by default: in dev, Vite proxies /api to the backend; in
  // production, set VITE_API_URL to the deployed API origin (e.g. https://api.example.com/api/v1).
  BASE_URL: import.meta.env.VITE_API_URL ?? '/api/v1',
  TIMEOUT: 60000,
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/auth/login',
      REGISTER: '/auth/register',
      REFRESH: '/auth/refresh',
      LOGOUT: '/auth/logout',
      ME: '/auth/me',
      VERIFY_EMAIL: '/auth/verify-email',
      SEND_VERIFICATION: '/auth/send-verification',
      FORGOT_PASSWORD: '/auth/forgot-password',
      RESET_PASSWORD: '/auth/reset-password',
      CHANGE_PASSWORD: '/auth/change-password',
    },
    USERS: {
      BASE: '/users',
      BY_ID: (id: string) => `/users/${id}`,
      BY_EMAIL: (email: string) => `/users/email/${email}`,
      PROFILE: (id: string) => `/users/${id}/profile`,
      PREFERENCES: (id: string) => `/users/${id}/preferences`,
      ACTIVATE: (id: string) => `/users/${id}/activate`,
      SUSPEND: (id: string) => `/users/${id}/suspend`,
      LOCK: (id: string) => `/users/${id}/lock`,
      UNLOCK: (id: string) => `/users/${id}/unlock`,
      ARCHIVE: (id: string) => `/users/${id}/archive`,
      RESTORE: (id: string) => `/users/${id}/restore`,
    },
    WORKSPACE: {
      PROFILE: '/workspace/profile',
      BRANDING: '/workspace/branding',
      SETTINGS: '/workspace/settings',
      LOGO_UPLOAD: '/workspace/logo',
      LOGO_DELETE: '/workspace/logo',
      FAVICON_UPLOAD: '/workspace/favicon',
      CLOSE: '/workspace/close',
    },
    ORGANIZATIONS: {
      BASE: '/organizations',
      BY_ID: (id: string) => `/organizations/${id}`,
      BY_SLUG: (slug: string) => `/organizations/slug/${slug}`,
      BRANDING: (id: string) => `/organizations/${id}/branding`,
      SETTINGS: (id: string) => `/organizations/${id}/settings`,
      APPROVE: (id: string) => `/organizations/${id}/approve`,
      SUSPEND: (id: string) => `/organizations/${id}/suspend`,
      REACTIVATE: (id: string) => `/organizations/${id}/reactivate`,
      ARCHIVE: (id: string) => `/organizations/${id}/archive`,
      RESTORE: (id: string) => `/organizations/${id}/restore`,
      ASSIGN_PRICING_TIER: (id: string) => `/organizations/${id}/pricing-tier`,
    },
    MEMBERSHIPS: {
      INVITE: '/memberships/invite',
      ACCEPT: '/memberships/accept',
      REVOKE: '/memberships/revoke',
      MEMBERS: (orgId: string) => `/organizations/${orgId}/members`,
      ROLE: (id: string) => `/memberships/${id}/role`,
      SUSPEND: (id: string) => `/memberships/${id}/suspend`,
      REACTIVATE: (id: string) => `/memberships/${id}/reactivate`,
      RESTORE: (id: string) => `/memberships/${id}/restore`,
      REMOVE: (id: string) => `/memberships/${id}`,
      USER_ORGS: (userId: string) => `/users/${userId}/organizations`,
    },
    ELECTIONS: {
      BASE: '/elections',
      BY_ID: (id: string) => `/elections/${id}`,
      STATS: '/elections/stats',
      CREATE: '/elections',
      UPDATE: (id: string) => `/elections/${id}`,
      DELETE: (id: string) => `/elections/${id}`,
      PUBLISH: (id: string) => `/elections/${id}/publish`,
      SCHEDULE_PUBLISH: (id: string) => `/elections/${id}/schedule-publish`,
      CANCEL_SCHEDULED_PUBLISH: (id: string) => `/elections/${id}/schedule-publish`,
      START: (id: string) => `/elections/${id}/start`,
      STOP: (id: string) => `/elections/${id}/stop`,
      CLOSE: (id: string) => `/elections/${id}/close`,
      ARCHIVE: (id: string) => `/elections/${id}/archive`,
      DUPLICATE: (id: string) => `/elections/${id}/duplicate`,
      ACTIVITIES: (id: string) => `/elections/${id}/activities`,
      AUDIT_LOGS: (id: string) => `/elections/${id}/audit-logs`,
      TIMELINE: (id: string) => `/elections/${id}/timeline`,
      BANNER_UPLOAD: (id: string) => `/elections/${id}/banner`,
      CANDIDATE_SLOTS: (id: string) => `/elections/${id}/candidate-slots`,
      LOGO_UPLOAD: (id: string) => `/elections/${id}/logo`,
      DRAFTS: {
        CREATE: '/elections/drafts',
        UPDATE: (id: string) => `/elections/drafts/${id}`,
      },
    },
    POSITIONS: {
      BASE: (electionId: string) => `/elections/${electionId}/positions`,
      BY_ID: (electionId: string, positionId: string) => `/elections/${electionId}/positions/${positionId}`,
      CREATE: (electionId: string) => `/elections/${electionId}/positions`,
      UPDATE: (electionId: string, positionId: string) => `/elections/${electionId}/positions/${positionId}`,
      DELETE: (electionId: string, positionId: string) => `/elections/${electionId}/positions/${positionId}`,
      REORDER: (electionId: string) => `/elections/${electionId}/positions/reorder`,
    },
    CANDIDATES: {
      BASE: (electionId: string, positionId: string) => `/elections/${electionId}/positions/${positionId}/candidates`,
      BY_ID: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}`,
      CREATE: (electionId: string, positionId: string) => `/elections/${electionId}/positions/${positionId}/candidates`,
      UPDATE: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}`,
      DELETE: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}`,
      SUBMIT: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}/submit`,
      APPROVE: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}/approve`,
      REJECT: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}/reject`,
      PUBLISH: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}/publish`,
      WITHDRAW: (electionId: string, positionId: string, candidateId: string) => `/elections/${electionId}/positions/${positionId}/candidates/${candidateId}/withdraw`,
      REORDER: (electionId: string, positionId: string) => `/elections/${electionId}/positions/${positionId}/candidates/reorder`,
    },
    VOTERS: {
      BASE: (electionId: string) => `/elections/${electionId}/voters`,
      ADD: (electionId: string) => `/elections/${electionId}/voters`,
      IMPORT: (electionId: string) => `/elections/${electionId}/voters/import`,
      CLEAR: (electionId: string) => `/elections/${electionId}/voters`,
    },
    VOTING: {
      BALLOT: (electionId: string) => `/elections/${electionId}/voting/ballot`,
      BALLOT_PREVIEW: (electionId: string) => `/elections/${electionId}/voting/ballot/preview`,
      BALLOT_GENERATE: (electionId: string) => `/elections/${electionId}/voting/ballot`,
      SESSION_START: (electionId: string) => `/elections/${electionId}/voting/session/start`,
      SESSION: (electionId: string) => `/elections/${electionId}/voting/session`,
      SESSION_CLOSE: (electionId: string, sessionId: string) => `/elections/${electionId}/voting/session/${sessionId}/close`,
      TOKEN_ISSUE: (electionId: string) => `/elections/${electionId}/voting/token/issue`,
      TOKEN_REVOKE: (electionId: string, tokenId: string) => `/elections/${electionId}/voting/tokens/${tokenId}`,
      VOTE: (electionId: string) => `/elections/${electionId}/voting/vote`,
      RECEIPT: (electionId: string, receiptCode: string) => `/elections/${electionId}/voting/receipt/${receiptCode}`,
      RECEIPT_UUID: (electionId: string, uuid: string) => `/elections/${electionId}/voting/receipts/${uuid}`,
      AUDIT_CHAIN: (electionId: string) => `/elections/${electionId}/voting/audit-chain`,
    },
    RESULTS: {
      BASE: (electionId: string) => `/elections/${electionId}/results`,
      PUBLISH: (electionId: string) => `/elections/${electionId}/publish-results`,
    },
    REGISTRATION: {
      SETTINGS: (electionId: string) => `/elections/${electionId}/registration/settings`,
      INFO: (slug: string) => `/elections/${slug}/registration/info`,
      LOOKUP: (slug: string) => `/elections/${slug}/registration/lookup`,
      REGISTER: (slug: string) => `/elections/${slug}/registration/register`,
      SEND_OTP: (uuid: string) => `/registration/${uuid}/send-otp`,
      VERIFY_OTP: (uuid: string) => `/registration/${uuid}/verify-otp`,
      COMPLETE: (uuid: string) => `/registration/${uuid}/complete`,
      STATUS: (uuid: string) => `/registration/${uuid}/status`,
      IMPORT: (electionId: string) => `/elections/${electionId}/voters/import`,
      TOGGLE: (electionId: string) => `/elections/${electionId}/registration/toggle`,
      START: (electionId: string) => `/elections/${electionId}/registration/start`,
      END: (electionId: string) => `/elections/${electionId}/registration/end`,
    },
    PASSES: {
      VALIDATE: (passId: string) => `/passes/${passId}/validate`,
      USE: (passId: string) => `/passes/${passId}/use`,
      INFO: (passId: string) => `/passes/${passId}`,
    },
    PUBLIC: {
      ELECTIONS: {
        BASE: '/public/elections',
        BY_SLUG: (slug: string) => `/public/elections/${slug}`,
        POSITIONS: (slug: string) => `/public/elections/${slug}/positions`,
        RESULTS: (slug: string) => `/public/elections/${slug}/results`,
        LIVE_RESULTS: (slug: string) => `/public/elections/${slug}/live-results`,
      },
      VOTING: {
        STATUS: (slug: string) => `/voting/${slug}/status`,
        SESSION_START: (slug: string) => `/voting/${slug}/session/start`,
        BALLOT: (slug: string) => `/voting/${slug}/ballot`,
        VOTE: (slug: string) => `/voting/${slug}/vote`,
      },
      RECEIPTS: {
        VERIFY: (code: string) => `/voting/verify/${code}`,
        SHOW: (code: string) => `/voting/receipt/${code}`,
      },
    },
    PLATFORM: {
      DASHBOARD: '/platform/dashboard',
      ANALYTICS: '/platform/analytics',
      BILLING: '/platform/billing',
      MONITORING_HEALTH: '/platform/monitoring/health',
      MONITORING_METRICS: '/platform/monitoring/metrics',
      MONITORING_SUMMARY: '/platform/monitoring/summary',
      MONITORING_INCIDENTS: '/platform/monitoring/incidents',
      MONITORING_DEPENDENCIES: '/platform/monitoring/dependencies',
      MONITORING_COLLECT: '/platform/monitoring/collect',
      COMMERCIAL_OVERVIEW: '/platform/commercial/overview',
      FINANCE_ANALYTICS: '/platform/finance/analytics',
      ORGANIZATIONS: '/platform/organizations',
      ORGANIZATION: (id: string) => `/platform/organizations/${id}`,
      ORGANIZATION_STORAGE: (id: string) => `/platform/organizations/${id}/storage`,
      ORGANIZATION_ACTIVITY: (id: string) => `/platform/organizations/${id}/activity`,
      ORGANIZATION_WORKSPACE: (id: string) => `/platform/organizations/${id}/workspace`,
      ORGANIZATION_SUBSCRIPTION: (id: string) => `/platform/organizations/${id}/subscription`,
      ORGANIZATION_SUBSCRIBE: (id: string) => `/platform/organizations/${id}/subscribe`,
      ORGANIZATION_AUDIT: (id: string) => `/platform/organizations/${id}/audit-logs`,
      ORGANIZATION_SUPPORT_TICKETS: (id: string) => `/platform/support/organizations/${id}/tickets`,
      SUSPEND_ORGANIZATION: (id: string) => `/platform/organizations/${id}/suspend`,
      WORKSPACE_CURRENT: (id: string) => `/platform/workspaces/${id}/current`,
      WORKSPACE_OPEN: (id: string) => `/platform/workspaces/${id}/open`,
      WORKSPACE_CLOSE: (id: string) => `/platform/workspaces/${id}/close`,
      WORKSPACE_VIEW: (id: string) => `/platform/workspaces/${id}/view`,
      WORKSPACE_SESSIONS: '/platform/workspace-sessions',
      ACTIVATE_ORGANIZATION: (id: string) => `/platform/organizations/${id}/activate`,
      USERS: '/platform/users',
      USER: (id: string) => `/platform/users/${id}`,
      USER_STATUS: (id: string) => `/platform/users/${id}/status`,
      USER_PASSWORD_RESET: (id: string) => `/platform/users/${id}/password-reset`,
      USER_AUDIT: (id: string) => `/platform/users/${id}/audit-logs`,
      STAFF: '/platform/staff',
      STAFF_MEMBER: (id: string) => `/platform/staff/${id}`,
      STAFF_STATUS: (id: string) => `/platform/staff/${id}/status`,
      STAFF_INVITATIONS: '/platform/staff/invitations',
      STAFF_INVITATION_REVOKE: (id: string) => `/platform/staff/invitations/${id}/revoke`,
      STAFF_INVITATION_RESEND: (id: string) => `/platform/staff/invitations/${id}/resend`,
      STAFF_PASSWORD_RESET: (id: string) => `/platform/staff/${id}/password-reset`,
      STAFF_PERMISSIONS: (id: string) => `/platform/staff/${id}/permissions`,
      STAFF_PERMISSION_GRANT: (id: string) => `/platform/staff/${id}/permissions/grant`,
      STAFF_PERMISSION_REVOKE: (id: string) => `/platform/staff/${id}/permissions/revoke`,
      STAFF_PERMISSION_REMOVE: (id: string, name: string) => `/platform/staff/${id}/permissions/${encodeURIComponent(name)}`,
      STAFF_PERMISSION_BREAKDOWN: (id: string) => `/platform/staff/${id}/permission-breakdown`,
      STAFF_UPDATE: (id: string) => `/platform/staff/${id}`,
      STAFF_DELETE: (id: string) => `/platform/staff/${id}`,
      INVITATION_ACCEPT: '/platform/invitations/accept',
      ME_PERMISSIONS: '/platform/me/permissions',
      ROLES_PERMISSIONS: '/platform/roles/permissions',
      ROLES: '/platform/roles',
      ROLE: (id: string) => `/platform/roles/${id}`,
      PLANS: '/platform/plans',
      PUBLIC_PLANS: '/platform/plans/public',
      PLAN: (id: string) => `/platform/plans/${id}`,
      SUBSCRIPTIONS: '/platform/subscriptions',
      SUBSCRIPTION: (id: string) => `/platform/subscriptions/${id}`,
      SUBSCRIPTION_CANCEL: (id: string) => `/platform/subscriptions/${id}/cancel`,
      AUDIT_LOGS: '/platform/audit-logs',
      AUDIT_EVENTS: '/platform/audit-logs/events',
      NOTIFICATIONS: '/platform/notifications',
      NOTIFICATIONS_UNREAD_COUNT: '/platform/notifications/unread-count',
      NOTIFICATIONS_MARK_ALL_READ: '/platform/notifications/read-all',
      NOTIFICATION: (id: string) => `/platform/notifications/${id}`,
      NOTIFICATION_READ: (id: string) => `/platform/notifications/${id}/read`,
      SUPPORT_TICKETS: '/platform/support/tickets',
      SUPPORT_TICKET: (id: string) => `/platform/support/tickets/${id}`,
      SUPPORT_TICKET_REPLY: (id: string) => `/platform/support/tickets/${id}/reply`,
      SUPPORT_TICKET_ACCEPT: (id: string) => `/platform/support/tickets/${id}/accept`,
      SUPPORT_TICKET_APPEAL_DECISION: (id: string) => `/platform/support/tickets/${id}/appeal-decision`,
      SUPPORT_TICKET_UPDATE: (id: string) => `/platform/support/tickets/${id}`,
      SUPPORT_UPLOAD: '/platform/support/upload',
      SUPPORT_ANALYTICS: '/platform/support/analytics',
      APPROVE_ELECTION: (id: string) => `/platform/elections/${id}/approve`,
      REJECT_ELECTION: (id: string) => `/platform/elections/${id}/reject`,
      ELECTIONS: '/platform/elections',
      REPORTS: '/platform/reports',
      REPORT: (key: string) => `/platform/reports/${key}`,
      SETTINGS: '/platform/settings',
      SETTINGS_PUBLIC: '/platform/settings/public',
      HELP_ARTICLES: '/platform/help/articles',
      HELP_ARTICLE: (id: string) => `/platform/help/articles/${id}`,
      EVENT_TEMPLATES: '/platform/event-templates',
      EVENT_TEMPLATE: (id: string) => `/platform/event-templates/${id}`,
      PRICING_TIERS: '/platform/pricing/tiers',
      PRICING_TIER: (id: string) => `/platform/pricing/tiers/${id}`,
      PRICING_TIER_TOGGLE: (id: string) => `/platform/pricing/tiers/${id}/toggle`,
      PRICING_TIER_ARCHIVE: (id: string) => `/platform/pricing/tiers/${id}/archive`,
      PRICING_TIER_RESTORE: (id: string) => `/platform/pricing/tiers/${id}/restore`,
      PRICING_TIERS_PUBLIC: '/platform/pricing/tiers/public',
      PAYMENTS: '/platform/payments',
      FREE_EVENT_FLAGS: '/platform/free-event/flags',
      FREE_EVENT_FLAG: (id: string) => `/platform/free-event/flags/${id}`,
      FREE_EVENT_FLAG_RESOLVE: (id: string) => `/platform/free-event/flags/${id}/resolve`,
      FREE_EVENT_FLAG_BLOCK: (id: string) => `/platform/free-event/flags/${id}/block`,
      FREE_EVENT_FLAG_UNBLOCK: (id: string) => `/platform/free-event/flags/${id}/unblock`,
      // Security Operations Center
      SECURITY_DASHBOARD: '/platform/security/dashboard',
      SECURITY_REALTIME: '/platform/security/realtime',
      SECURITY_ACTIVITY_GRAPH: '/platform/security/activity-graph',
      SECURITY_ACTIVITY_STREAM: '/platform/security/activity-stream',
      SECURITY_TELEMETRY_HEALTH: '/platform/security/telemetry-health',
      SECURITY_EVENTS: '/platform/security/events',
      SECURITY_EVENT: (id: string) => `/platform/security/events/${id}`,
      SECURITY_INCIDENTS: '/platform/security/incidents',
      SECURITY_INCIDENT: (id: string) => `/platform/security/incidents/${id}`,
      SECURITY_INCIDENT_TIMELINE: (id: string) => `/platform/security/incidents/${id}/timeline`,
      SECURITY_INCIDENT_STATUS: (id: string) => `/platform/security/incidents/${id}/status`,
      SECURITY_INCIDENT_ESCALATE: (id: string) => `/platform/security/incidents/${id}/escalate`,
      SECURITY_ALERTS: '/platform/security/alerts',
      SECURITY_ALERT_ACKNOWLEDGE: (id: string) => `/platform/security/alerts/${id}/acknowledge`,
      SECURITY_ALERT_RESOLVE: (id: string) => `/platform/security/alerts/${id}/resolve`,
      SECURITY_ALERT_FALSE_POSITIVE: (id: string) => `/platform/security/alerts/${id}/false-positive`,
      SECURITY_ORGS_ATTENTION: '/platform/security/organizations/attention',
      SECURITY_EMAIL_ACTIVITY: '/platform/security/email-activity',
      SECURITY_API_MONITOR: '/platform/security/api-monitor',
    },
    INVITATIONS_PUBLIC: {
      SHOW: (token: string) => `/invitations/${token}`,
      ACCEPT: (token: string) => `/invitations/${token}/accept`,
    },
    ORG: {
      TEAM: '/org/team',
      TEAM_INVITATIONS: '/org/team/invitations',
      TEAM_ROLE_OPTIONS: '/org/team/role-options',
      TEAM_MEMBER_ROLE: (id: string) => `/org/team/${id}/role`,
      TEAM_MEMBER: (id: string) => `/org/team/${id}`,
      TEAM_TRANSFER_OWNERSHIP: (id: string) => `/org/team/${id}/transfer-ownership`,
      ME_PERMISSIONS: '/org/me/permissions',
      ROLES_PERMISSIONS: '/org/roles/permissions',
      ROLES: '/org/roles',
      ROLE: (id: string) => `/org/roles/${id}`,
      AUDIT_LOGS: '/org/audit-logs',
      AUDIT_EVENTS: '/org/audit-logs/events',
      REPORTS: '/org/reports',
      REPORT: (key: string) => `/org/reports/${key}`,
      TEMPLATES: '/org/templates',
      TEMPLATE: (id: string) => `/org/templates/${id}`,
      ARCHIVE: '/org/archive',
      ARCHIVE_RESTORE: (id: string) => `/org/archive/${id}/restore`,
      HELP_ARTICLES: '/org/help/articles',
      HELP_CATEGORIES: '/org/help/categories',
      HELP_ARTICLE: (id: string) => `/org/help/articles/${id}`,
      NOTIFICATIONS: '/org/notifications',
      NOTIFICATIONS_POLL: '/org/notifications/poll',
      NOTIFICATIONS_UNREAD_COUNT: '/org/notifications/unread-count',
      NOTIFICATION_PREFERENCES: '/org/notifications/preferences',
      NOTIFICATION_READ: (id: string) => `/org/notifications/${id}/read`,
      NOTIFICATION_DISMISS: (id: string) => `/org/notifications/${id}/dismiss`,
      BILLING: '/org/billing',
      BILLING_PLANS: '/org/billing/plans',
      BILLING_CANCEL: '/org/billing/cancel',
      BILLING_OVERVIEW: '/org/billing/overview',
      BILLING_QUOTE: '/org/billing/quote',
      EVENT_BILLING: (electionId: string) => `/org/elections/${electionId}/billing`,
      EVENT_BILLING_CAPACITY: (electionId: string) => `/org/elections/${electionId}/billing/capacity`,
      EVENT_BILLING_CAPACITY_CONSENT: (electionId: string) => `/org/elections/${electionId}/billing/capacity-consent`,
      EVENT_BILLING_UPGRADE: (electionId: string) => `/org/elections/${electionId}/billing/upgrade`,
      EVENT_BILLING_PAY: (electionId: string) => `/org/elections/${electionId}/billing/pay`,
      PAYMENT_VERIFY: (paymentId: string) => `/org/payments/${paymentId}/verify`,
      PAYMENTS: '/org/payments',
      SUPPORT_TICKETS: '/org/support/tickets',
      SUPPORT_TICKET: (id: string) => `/org/support/tickets/${id}`,
      SUPPORT_TICKET_REPLY: (id: string) => `/org/support/tickets/${id}/reply`,
      SUPPORT_UPLOAD: '/org/support/upload',
      INVITATION_SHOW: (token: string) => `/org/invitations/${token}`,
      INVITATION_ACCEPT: (token: string) => `/org/invitations/${token}/accept`,
    },
  },
} as const;
