/// <reference types="vite/client" />

export const API = {
  BASE_URL: import.meta.env.VITE_API_URL ?? 'http://localhost:3001/api/v1',
  TIMEOUT: 30000,
  ENDPOINTS: {
    AUTH: {
      LOGIN: '/auth/login',
      REGISTER: '/auth/register',
      REFRESH: '/auth/refresh',
      LOGOUT: '/auth/logout',
      ME: '/auth/me',
      VERIFY_EMAIL: '/auth/verify-email',
      SEND_VERIFICATION: '/auth/send-verification',
      FORGOT_PASSWORD: '/auth/forgot-password',
      RESET_PASSWORD: '/auth/reset-password',
      CHANGE_PASSWORD: '/auth/change-password',
    },
    USERS: {
      BASE: '/users',
      BY_ID: (id: string) => `/users/${id}`,
      BY_EMAIL: (email: string) => `/users/email/${email}`,
      PROFILE: (id: string) => `/users/${id}/profile`,
      PREFERENCES: (id: string) => `/users/${id}/preferences`,
      ACTIVATE: (id: string) => `/users/${id}/activate`,
      SUSPEND: (id: string) => `/users/${id}/suspend`,
      LOCK: (id: string) => `/users/${id}/lock`,
      UNLOCK: (id: string) => `/users/${id}/unlock`,
      ARCHIVE: (id: string) => `/users/${id}/archive`,
      RESTORE: (id: string) => `/users/${id}/restore`,
    },
    ORGANIZATIONS: {
      BASE: '/organizations',
      BY_ID: (id: string) => `/organizations/${id}`,
      BY_SLUG: (slug: string) => `/organizations/slug/${slug}`,
      BRANDING: (id: string) => `/organizations/${id}/branding`,
      SETTINGS: (id: string) => `/organizations/${id}/settings`,
      APPROVE: (id: string) => `/organizations/${id}/approve`,
      SUSPEND: (id: string) => `/organizations/${id}/suspend`,
      REACTIVATE: (id: string) => `/organizations/${id}/reactivate`,
      ARCHIVE: (id: string) => `/organizations/${id}/archive`,
      RESTORE: (id: string) => `/organizations/${id}/restore`,
    },
    MEMBERSHIPS: {
      INVITE: '/memberships/invite',
      ACCEPT: '/memberships/accept',
      REVOKE: '/memberships/revoke',
      MEMBERS: (orgId: string) => `/organizations/${orgId}/members`,
      ROLE: (id: string) => `/memberships/${id}/role`,
      SUSPEND: (id: string) => `/memberships/${id}/suspend`,
      REACTIVATE: (id: string) => `/memberships/${id}/reactivate`,
      RESTORE: (id: string) => `/memberships/${id}/restore`,
      REMOVE: (id: string) => `/memberships/${id}`,
      USER_ORGS: (userId: string) => `/users/${userId}/organizations`,
    },
    ELECTIONS: {
      BASE: '/elections',
      BY_ID: (id: string) => `/elections/${id}`,
      STATS: '/elections/stats',
      CREATE: '/elections',
      UPDATE: (id: string) => `/elections/${id}`,
      DELETE: (id: string) => `/elections/${id}`,
      PUBLISH: (id: string) => `/elections/${id}/publish`,
      CLOSE: (id: string) => `/elections/${id}/close`,
      ARCHIVE: (id: string) => `/elections/${id}/archive`,
      ACTIVITIES: (id: string) => `/elections/${id}/activities`,
      TIMELINE: (id: string) => `/elections/${id}/timeline`,
    },
    CANDIDATES: {
      BASE: (electionId: string) => `/elections/${electionId}/candidates`,
      BY_ID: (electionId: string, candidateId: string) => `/elections/${electionId}/candidates/${candidateId}`,
      CREATE: (electionId: string) => `/elections/${electionId}/candidates`,
      UPDATE: (electionId: string, candidateId: string) => `/elections/${electionId}/candidates/${candidateId}`,
      DELETE: (electionId: string, candidateId: string) => `/elections/${electionId}/candidates/${candidateId}`,
    },
    VOTERS: {
      BASE: (electionId: string) => `/elections/${electionId}/voters`,
      ADD: (electionId: string) => `/elections/${electionId}/voters`,
      REMOVE: (electionId: string, voterId: string) => `/elections/${electionId}/voters/${voterId}`,
      IMPORT: (electionId: string) => `/elections/${electionId}/voters/import`,
    },
    BALLOTS: {
      CAST: (electionId: string) => `/elections/${electionId}/ballots`,
      VERIFY: (electionId: string, voterId: string) => `/elections/${electionId}/ballots/verify/${voterId}`,
      RECEIPT: (electionId: string, voterId: string) => `/elections/${electionId}/ballots/receipt/${voterId}`,
    },
    RESULTS: {
      BASE: (electionId: string) => `/elections/${electionId}/results`,
      PUBLISH: (electionId: string) => `/elections/${electionId}/results/publish`,
    },
    REGISTRATION: {
      SETTINGS: (electionId: string) => `/elections/${electionId}/registration/settings`,
      INFO: (slug: string) => `/elections/${slug}/registration/info`,
      LOOKUP: (slug: string) => `/elections/${slug}/registration/lookup`,
      REGISTER: (slug: string) => `/elections/${slug}/registration`,
      SEND_OTP: (uuid: string) => `/registrations/${uuid}/send-otp`,
      VERIFY_OTP: (uuid: string) => `/registrations/${uuid}/verify-otp`,
      COMPLETE: (uuid: string) => `/registrations/${uuid}/complete`,
      STATUS: (uuid: string) => `/registrations/${uuid}/status`,
      IMPORT: (electionId: string) => `/elections/${electionId}/registrations/import`,
      TOGGLE: (electionId: string) => `/elections/${electionId}/registration/toggle`,
    },
    PASSES: {
      VALIDATE: (passId: string) => `/passes/${passId}/validate`,
      USE: (passId: string) => `/passes/${passId}/use`,
      INFO: (passId: string) => `/passes/${passId}`,
    },
    NOTIFICATIONS: {
      BASE: '/notifications',
      MARK_READ: (id: string) => `/notifications/${id}/read`,
      MARK_ALL_READ: '/notifications/read-all',
      PREFERENCES: '/notifications/preferences',
    },
    PLATFORM: {
      DASHBOARD: '/platform/dashboard',
      ANALYTICS: '/platform/analytics',
      ORGANIZATIONS: '/platform/organizations',
      ORGANIZATION: (id: string) => `/platform/organizations/${id}`,
      ORGANIZATION_STORAGE: (id: string) => `/platform/organizations/${id}/storage`,
      ORGANIZATION_ACTIVITY: (id: string) => `/platform/organizations/${id}/activity`,
      ORGANIZATION_WORKSPACE: (id: string) => `/platform/organizations/${id}/workspace`,
      ORGANIZATION_SUBSCRIPTION: (id: string) => `/platform/organizations/${id}/subscription`,
      ORGANIZATION_SUBSCRIBE: (id: string) => `/platform/organizations/${id}/subscribe`,
      ORGANIZATION_AUDIT: (id: string) => `/platform/organizations/${id}/audit-logs`,
      ORGANIZATION_SUPPORT_TICKETS: (id: string) => `/platform/support/organizations/${id}/tickets`,
      SUSPEND_ORGANIZATION: (id: string) => `/platform/organizations/${id}/suspend`,
      ACTIVATE_ORGANIZATION: (id: string) => `/platform/organizations/${id}/activate`,
      USERS: '/platform/users',
      USER: (id: string) => `/platform/users/${id}`,
      USER_STATUS: (id: string) => `/platform/users/${id}/status`,
      USER_AUDIT: (id: string) => `/platform/users/${id}/audit-logs`,
      STAFF: '/platform/staff',
      STAFF_MEMBER: (id: string) => `/platform/staff/${id}`,
      STAFF_STATUS: (id: string) => `/platform/staff/${id}/status`,
      STAFF_INVITATIONS: '/platform/staff/invitations',
      STAFF_INVITATION_REVOKE: (id: string) => `/platform/staff/invitations/${id}/revoke`,
      ROLES_PERMISSIONS: '/platform/roles/permissions',
      ROLES: '/platform/roles',
      ROLE: (id: string) => `/platform/roles/${id}`,
      PLANS: '/platform/plans',
      PUBLIC_PLANS: '/platform/plans/public',
      PLAN: (id: string) => `/platform/plans/${id}`,
      SUBSCRIPTIONS: '/platform/subscriptions',
      SUBSCRIPTION: (id: string) => `/platform/subscriptions/${id}`,
      AUDIT_LOGS: '/platform/audit-logs',
      AUDIT_EVENTS: '/platform/audit-logs/events',
      NOTIFICATIONS: '/platform/notifications',
      NOTIFICATION: (id: string) => `/platform/notifications/${id}`,
      SUPPORT_TICKETS: '/platform/support/tickets',
      SUPPORT_TICKET: (id: string) => `/platform/support/tickets/${id}`,
      SUPPORT_TICKET_REPLY: (id: string) => `/platform/support/tickets/${id}/reply`,
      SUPPORT_TICKET_UPDATE: (id: string) => `/platform/support/tickets/${id}`,
      REPORTS: '/platform/reports',
      REPORT: (key: string) => `/platform/reports/${key}`,
      SETTINGS: '/platform/settings',
      SETTINGS_PUBLIC: '/platform/settings/public',
      HELP_ARTICLES: '/platform/help/articles',
      HELP_ARTICLE: (id: string) => `/platform/help/articles/${id}`,
      EVENT_TEMPLATES: '/platform/event-templates',
      EVENT_TEMPLATE: (id: string) => `/platform/event-templates/${id}`,
    },
    ORG: {
      TEAM: '/org/team',
      TEAM_INVITATIONS: '/org/team/invitations',
      TEAM_ROLE_OPTIONS: '/org/team/role-options',
      TEAM_MEMBER_ROLE: (id: string) => `/org/team/${id}/role`,
      TEAM_MEMBER: (id: string) => `/org/team/${id}`,
      TEAM_TRANSFER_OWNERSHIP: (id: string) => `/org/team/${id}/transfer-ownership`,
      ROLES_PERMISSIONS: '/org/roles/permissions',
      ROLES: '/org/roles',
      ROLE: (id: string) => `/org/roles/${id}`,
      AUDIT_LOGS: '/org/audit-logs',
      AUDIT_EVENTS: '/org/audit-logs/events',
      REPORTS: '/org/reports',
      REPORT: (key: string) => `/org/reports/${key}`,
      TEMPLATES: '/org/templates',
      TEMPLATE: (id: string) => `/org/templates/${id}`,
      ARCHIVE: '/org/archive',
      ARCHIVE_RESTORE: (id: string) => `/org/archive/${id}/restore`,
      HELP_ARTICLES: '/org/help/articles',
      HELP_CATEGORIES: '/org/help/categories',
      HELP_ARTICLE: (id: string) => `/org/help/articles/${id}`,
      NOTIFICATIONS: '/org/notifications',
      NOTIFICATIONS_UNREAD_COUNT: '/org/notifications/unread-count',
      NOTIFICATION_READ: (id: string) => `/org/notifications/${id}/read`,
      NOTIFICATION_DISMISS: (id: string) => `/org/notifications/${id}/dismiss`,
      BILLING: '/org/billing',
      BILLING_PLANS: '/org/billing/plans',
      BILLING_CANCEL: '/org/billing/cancel',
      SUPPORT_TICKETS: '/org/support/tickets',
      SUPPORT_TICKET: (id: string) => `/org/support/tickets/${id}`,
      SUPPORT_TICKET_REPLY: (id: string) => `/org/support/tickets/${id}/reply`,
      INVITATION_SHOW: (token: string) => `/org/invitations/${token}`,
      INVITATION_ACCEPT: (token: string) => `/org/invitations/${token}/accept`,
    },
  },
} as const;
