export const COUNTRY_STATES: Record<string, string[]> = {
  // Africa
  Nigeria: [
    "Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno",
    "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "FCT (Abuja)", "Gombe",
    "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos",
    "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers",
    "Sokoto", "Taraba", "Yobe", "Zamfara",
  ],
  Ghana: [
    "Ahafo", "Ashanti", "Bono", "Bono East", "Central", "Eastern", "Greater Accra",
    "North East", "Northern", "Oti", "Savannah", "Upper East", "Upper West",
    "Volta", "Western", "Western North",
  ],
  Kenya: [
    "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo-Marakwet", "Embu", "Garissa",
    "Homa Bay", "Isiolo", "Kajiado", "Kakamega", "Kericho", "Kiambu", "Kilifi",
    "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu",
    "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Migori", "Mombasa",
    "Murang'a", "Nairobi", "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua",
    "Nyeri", "Samburu", "Siaya", "Taita-Taveta", "Tana River", "Tharaka-Nithi",
    "Trans-Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot",
  ],
  "South Africa": [
    "Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo",
    "Mpumalanga", "North West", "Northern Cape", "Western Cape",
  ],
  Uganda: ["Central", "Eastern", "Northern", "Western"],
  Tanzania: [
    "Arusha", "Dar es Salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi",
    "Kigoma", "Kilimanjaro", "Lindi", "Manyara", "Mara", "Mbeya", "Morogoro",
    "Mtwara", "Mwanza", "Njombe", "Pemba North", "Pemba South", "Pwani",
    "Rukwa", "Ruvuma", "Shinyanga", "Simiyu", "Singida", "Songwe", "Tabora",
    "Tanga", "Zanzibar North", "Zanzibar South", "Zanzibar West",
  ],
  Ethiopia: [
    "Addis Ababa", "Afar", "Amhara", "Benishangul-Gumuz", "Dire Dawa",
    "Gambela", "Harari", "Oromia", "Sidama", "Somali", "South West Ethiopia",
    "Southern Nations", "Tigray",
  ],
  Rwanda: ["City of Kigali", "Eastern", "Northern", "Southern", "Western"],
  Senegal: [
    "Dakar", "Diourbel", "Fatick", "Kaffrine", "Kaolack", "Kédougou", "Kolda",
    "Louga", "Matam", "Saint-Louis", "Sédhiou", "Tambacounda", "Thiès", "Ziguinchor",
  ],
  Cameroon: [
    "Adamawa", "Centre", "East", "Far North", "Littoral", "North",
    "North West", "South", "South West", "West",
  ],
  Egypt: [
    "Alexandria", "Aswan", "Asyut", "Beheira", "Beni Suef", "Cairo", "Dakahlia",
    "Damietta", "Faiyum", "Gharbia", "Giza", "Ismailia", "Kafr El Sheikh",
    "Luxor", "Matrouh", "Minya", "Monufia", "New Valley", "North Sinai",
    "Port Said", "Qalyubia", "Qena", "Red Sea", "Sharqia", "Sohag",
    "South Sinai", "Suez",
  ],
  Morocco: [
    "Béni Mellal-Khénifra", "Casablanca-Settat", "Dakhla-Oued Ed-Dahab",
    "Drâa-Tafilalet", "Fès-Meknès", "Guelmim-Oued Noun", "Laâyoune-Sakia El Hamra",
    "Marrakech-Safi", "Oriental", "Rabat-Salé-Kénitra", "Souss-Massa",
    "Tanger-Tétouan-Al Hoceïma",
  ],
  Algeria: [
    "Adrar", "Aïn Defla", "Aïn Témouchent", "Algiers", "Annaba", "Batna",
    "Béchar", "Béjaïa", "Biskra", "Blida", "Bordj Bou Arréridj", "Bouïra",
    "Boumerdès", "Chlef", "Constantine", "Djelfa", "El Bayadh", "El Oued",
    "El Tarf", "Ghardaïa", "Guelma", "Illizi", "Jijel", "Khenchela",
    "Laghouat", "Mascara", "Médéa", "Mila", "Mostaganem", "Msila", "Naâma",
    "Oran", "Ouargla", "Oum El Bouaghi", "Relizane", "Saïda", "Sétif",
    "Sidi Bel Abbès", "Skikda", "Souk Ahras", "Tamanrasset", "Tébessa",
    "Tiaret", "Tindouf", "Tipaza", "Tissemsilt", "Tizi Ouzou", "Tlemcen",
  ],
  Angola: [
    "Bengo", "Benguela", "Bié", "Cabinda", "Cuando Cubango", "Cuanza Norte",
    "Cuanza Sul", "Cunene", "Huambo", "Huíla", "Luanda", "Lunda Norte",
    "Lunda Sul", "Malanje", "Moxico", "Namibe", "Uíge", "Zaire",
  ],
  Botswana: [
    "Central", "Chobe", "Francistown", "Gaborone", "Ghanzi", "Jwaneng",
    "Kgalagadi", "Kgatleng", "Kweneng", "Lobatse", "Ngamiland", "North-East",
    "Selibe Phikwe", "South-East", "Sowa", "Southern",
  ],
  "Côte d'Ivoire": [
    "Abidjan", "Bas-Sassandra", "Comoé", "Denguélé", "Gôh-Djiboua",
    "Lacs", "Lagunes", "Montagnes", "Sassandra-Marahoué", "Savanes",
    "Vallée du Bandama", "Woroba", "Yamoussoukro", "Zanzan",
  ],
  "DR Congo": [
    "Bas-Uélé", "Équateur", "Haut-Katanga", "Haut-Lomami", "Haut-Uélé",
    "Ituri", "Kasaï", "Kasaï Central", "Kasaï Oriental", "Kinshasa",
    "Kongo Central", "Kwango", "Kwilu", "Lomami", "Lualaba",
    "Mai-Ndombe", "Maniema", "Mongala", "Nord-Kivu", "Nord-Ubangi",
    "Sankuru", "Sud-Kivu", "Sud-Ubangi", "Tanganyika", "Tshopo", "Tshuapa",
  ],
  Libya: [
    "Al Wahat", "Al Jabal al Akhdar", "Al Marj", "Al Murgub", "An Nuqat al Khams",
    "Benghazi", "Derna", "Ghat", "Jabal al Gharbi", "Jafara", "Jufra",
    "Kufra", "Marzooq", "Misrata", "Murqub", "Nalut", "Nuqat al Khams",
    "Sabha", "Sirte", "Tripoli", "Wadi al Hayaa", "Wadi al Shatii", "Zawiya",
  ],
  Malawi: [
    "Balaka", "Blantyre", "Chikwawa", "Chiradzulu", "Chitipa", "Dedza",
    "Dowa", "Karonga", "Kasungu", "Likoma", "Lilongwe", "Machinga",
    "Mangochi", "Mchinji", "Mulanje", "Mwanza", "Mzimba", "Neno",
    "Nkhata Bay", "Nkhotakota", "Nsanje", "Ntcheu", "Ntchisi", "Phalombe",
    "Rumphi", "Salima", "Thyolo", "Zomba",
  ],
  Mali: [
    "Bamako", "Gao", "Kayes", "Kidal", "Koulikoro", "Ménaka", "Mopti",
    "Ségou", "Sikasso", "Taoudénit", "Tombouctou",
  ],
  Mauritius: ["Agalega", "Black River", "Cargados Carajos", "Flacq", "Grand Port", "Moka", "Pamplemousses", "Plaines Wilhems", "Port Louis", "Rivière du Rempart", "Rodrigues", "Savanne"],
  Mozambique: [
    "Cabo Delgado", "Gaza", "Inhambane", "Manica", "Maputo", "Maputo City",
    "Nampula", "Niassa", "Sofala", "Tete", "Zambézia",
  ],
  Namibia: [
    "Erongo", "Hardap", "Karas", "Kavango East", "Kavango West", "Khomas",
    "Kunene", "Ohangwena", "Omaheke", "Omusati", "Oshana", "Oshikoto",
    "Otjozondjupa", "Zambezi",
  ],
  Niger: [
    "Agadez", "Diffa", "Dosso", "Maradi", "Niamey", "Tahoua", "Tillabéri", "Zinder",
  ],
  Sudan: [
    "Al Jazirah", "Al Qadarif", "Blue Nile", "Central Darfur", "East Darfur",
    "Kassala", "Khartoum", "North Darfur", "North Kordofan", "Northern",
    "Red Sea", "River Nile", "Sennar", "South Darfur", "South Kordofan",
    "West Darfur", "West Kordofan", "White Nile",
  ],
  Tunisia: [
    "Ariana", "Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba",
    "Kairouan", "Kasserine", "Kébili", "La Manouba", "Mahdia", "Médenine",
    "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse",
    "Tataouine", "Tozeur", "Tunis", "Zaghouan",
  ],
  Zambia: [
    "Central", "Copperbelt", "Eastern", "Luapula", "Lusaka", "Muchinga",
    "Northern", "North-Western", "Southern", "Western",
  ],
  Zimbabwe: [
    "Bulawayo", "Harare", "Manicaland", "Mashonaland Central",
    "Mashonaland East", "Mashonaland West", "Masvingo",
    "Matabeleland North", "Matabeleland South", "Midlands",
  ],

  // North America
  "United States": [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado",
    "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho",
    "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana",
    "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota",
    "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada",
    "New Hampshire", "New Jersey", "New Mexico", "New York",
    "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon",
    "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
    "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington",
    "West Virginia", "Wisconsin", "Wyoming",
  ],
  Canada: [
    "Alberta", "British Columbia", "Manitoba", "New Brunswick",
    "Newfoundland and Labrador", "Nova Scotia", "Ontario",
    "Prince Edward Island", "Quebec", "Saskatchewan",
    "Northwest Territories", "Nunavut", "Yukon",
  ],
  Mexico: [
    "Aguascalientes", "Baja California", "Baja California Sur", "Campeche",
    "Chiapas", "Chihuahua", "Ciudad de México", "Coahuila", "Colima",
    "Durango", "Estado de México", "Guanajuato", "Guerrero", "Hidalgo",
    "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca",
    "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa",
    "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas",
  ],
  Cuba: [
    "Artemisa", "Camagüey", "Ciego de Ávila", "Cienfuegos", "Granma",
    "Guantánamo", "Holguín", "Isla de la Juventud", "La Habana",
    "Las Tunas", "Matanzas", "Mayabeque", "Pinar del Río", "Sancti Spíritus",
    "Santiago de Cuba", "Villa Clara",
  ],
  Guatemala: [
    "Alta Verapaz", "Baja Verapaz", "Chimaltenango", "Chiquimula", "El Progreso",
    "Escuintla", "Guatemala", "Huehuetenango", "Izabal", "Jalapa", "Jutiapa",
    "Petén", "Quetzaltenango", "Quiché", "Retalhuleu", "Sacatepéquez",
    "San Marcos", "Santa Rosa", "Sololá", "Suchitepéquez", "Totonicapán", "Zacapa",
  ],
  Jamaica: [
    "Clarendon", "Hanover", "Kingston", "Manchester", "Portland", "Saint Andrew",
    "Saint Ann", "Saint Catherine", "Saint Elizabeth", "Saint James",
    "Saint Mary", "Saint Thomas", "Trelawny", "Westmoreland",
  ],
  "Dominican Republic": [
    "Azua", "Baoruco", "Barahona", "Dajabón", "Distrito Nacional", "Duarte",
    "El Seibo", "Elías Piña", "Espaillat", "Hato Mayor", "Hermanas Mirabal",
    "Independencia", "La Altagracia", "La Romana", "La Vega", "María Trinidad Sánchez",
    "Monseñor Nouel", "Monte Cristi", "Monte Plata", "Pedernales", "Peravia",
    "Puerto Plata", "Samaná", "San Cristóbal", "San José de Ocoa", "San Juan",
    "San Pedro de Macorís", "Sánchez Ramírez", "Santiago", "Santiago Rodríguez",
    "Santo Domingo", "Valverde",
  ],
  "Costa Rica": [
    "Alajuela", "Cartago", "Guanacaste", "Heredia", "Limón", "Puntarenas", "San José",
  ],
  Panama: [
    "Bocas del Toro", "Chiriquí", "Coclé", "Colón", "Darién", "Emberá",
    "Guna Yala", "Herrera", "Los Santos", "Ngäbe-Buglé", "Panamá",
    "Panamá Oeste", "Veraguas",
  ],
  "Trinidad and Tobago": [
    "Arima", "Chaguanas", "Couva–Tabaquite–Talparo", "Diego Martin",
    "Mayaro–Rio Claro", "Penal–Debe", "Point Fortin", "Port of Spain",
    "Princes Town", "San Fernando", "San Juan–Laventille", "Sangre Grande",
    "Siparia", "Tobago", "Tunapuna–Piarco",
  ],

  // South America
  Brazil: [
    "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará",
    "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão",
    "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará",
    "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro",
    "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima",
    "Santa Catarina", "São Paulo", "Sergipe", "Tocantins",
  ],
  Argentina: [
    "Buenos Aires", "Buenos Aires City", "Catamarca", "Chaco", "Chubut",
    "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa",
    "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta",
    "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero",
    "Tierra del Fuego", "Tucumán",
  ],
  Colombia: [
    "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá",
    "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó",
    "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira",
    "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo",
    "Quindío", "Risaralda", "San Andrés y Providencia", "Santander",
    "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada",
  ],
  Chile: [
    "Arica y Parinacota", "Tarapacá", "Antofagasta", "Atacama", "Coquimbo",
    "Valparaíso", "Metropolitana", "O'Higgins", "Maule", "Ñuble", "Biobío",
    "La Araucanía", "Los Ríos", "Los Lagos", "Aysén", "Magallanes",
  ],
  Peru: [
    "Amazonas", "Áncash", "Apurímac", "Arequipa", "Ayacucho", "Cajamarca",
    "Callao", "Cusco", "Huancavelica", "Huánuco", "Ica", "Junín", "La Libertad",
    "Lambayeque", "Lima", "Loreto", "Madre de Dios", "Moquegua", "Pasco",
    "Piura", "Puno", "San Martín", "Tacna", "Tumbes", "Ucayali",
  ],
  Venezuela: [
    "Amazonas", "Anzoátegui", "Apure", "Aragua", "Barinas", "Bolívar",
    "Carabobo", "Cojedes", "Delta Amacuro", "Distrito Capital", "Falcón",
    "Guárico", "Lara", "La Guaira", "Mérida", "Miranda", "Monagas",
    "Nueva Esparta", "Portuguesa", "Sucre", "Táchira", "Trujillo", "Yaracuy", "Zulia",
  ],
  Ecuador: [
    "Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro",
    "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja", "Los Ríos",
    "Manabí", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha",
    "Santa Elena", "Santo Domingo de los Tsáchilas", "Sucumbíos", "Tungurahua", "Zamora Chinchipe",
  ],
  Bolivia: [
    "Beni", "Chuquisaca", "Cochabamba", "La Paz", "Oruro", "Pando", "Potosí",
    "Santa Cruz", "Tarija",
  ],
  Uruguay: [
    "Artigas", "Canelones", "Cerro Largo", "Colonia", "Durazno", "Flores",
    "Florida", "Lavalleja", "Maldonado", "Montevideo", "Paysandú",
    "Río Negro", "Rivera", "Rocha", "Salto", "San José", "Soriano",
    "Tacuarembó", "Treinta y Tres",
  ],
  Paraguay: [
    "Alto Paraguay", "Alto Paraná", "Amambay", "Asunción", "Boquerón",
    "Caaguazú", "Caazapá", "Canindeyú", "Central", "Concepción",
    "Cordillera", "Guairá", "Itapúa", "Misiones", "Ñeembucú",
    "Paraguarí", "Presidente Hayes", "San Pedro",
  ],

  // Europe
  "United Kingdom": [
    "England", "Northern Ireland", "Scotland", "Wales",
  ],
  Germany: [
    "Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen",
    "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland",
    "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia",
  ],
  France: [
    "Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Brittany",
    "Centre-Val de Loire", "Corsica", "Grand Est", "Hauts-de-France",
    "Île-de-France", "Normandy", "Nouvelle-Aquitaine", "Occitanie",
    "Pays de la Loire", "Provence-Alpes-Côte d'Azur",
  ],
  Italy: [
    "Abruzzo", "Aosta Valley", "Apulia", "Basilicata", "Calabria", "Campania",
    "Emilia-Romagna", "Friuli-Venezia Giulia", "Lazio", "Liguria", "Lombardy",
    "Marche", "Molise", "Piedmont", "Sardinia", "Sicily", "Trentino-Alto Adige",
    "Tuscany", "Umbria", "Veneto",
  ],
  Spain: [
    "Andalusia", "Aragon", "Asturias", "Balearic Islands", "Basque Country",
    "Canary Islands", "Cantabria", "Castile and León", "Castilla-La Mancha",
    "Catalonia", "Community of Madrid", "Extremadura", "Galicia", "La Rioja",
    "Navarre", "Region of Murcia", "Valencian Community",
  ],
  Netherlands: [
    "Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg",
    "North Brabant", "North Holland", "Overijssel", "South Holland", "Utrecht", "Zeeland",
  ],
  Switzerland: [
    "Aargau", "Appenzell Ausserrhoden", "Appenzell Innerrhoden", "Basel-Landschaft",
    "Basel-Stadt", "Bern", "Fribourg", "Geneva", "Glarus", "Graubünden", "Jura",
    "Lucerne", "Neuchâtel", "Nidwalden", "Obwalden", "Schaffhausen", "Schwyz",
    "Solothurn", "St. Gallen", "Thurgau", "Ticino", "Uri", "Valais", "Vaud", "Zug", "Zürich",
  ],
  Sweden: [
    "Blekinge", "Dalarna", "Gävleborg", "Gotland", "Halland", "Jämtland",
    "Jönköping", "Kalmar", "Kronoberg", "Norrbotten", "Örebro", "Östergötland",
    "Skåne", "Södermanland", "Stockholm", "Uppsala", "Värmland", "Västerbotten",
    "Västernorrland", "Västmanland", "Västra Götaland",
  ],
  Norway: [
    "Agder", "Innlandet", "Møre og Romsdal", "Nordland", "Oslo", "Rogaland",
    "Troms og Finnmark", "Trøndelag", "Vestfold og Telemark", "Vestland", "Viken",
  ],
  Denmark: [
    "Capital Region", "Central Jutland", "North Jutland", "Region Zealand", "Southern Denmark",
  ],
  Finland: [
    "Åland", "Central Finland", "Central Ostrobothnia", "Kainuu", "Kanta-Häme",
    "Kymenlaakso", "Lapland", "North Karelia", "North Ostrobothnia", "North Savo",
    "Ostrobothnia", "Päijät-Häme", "Pirkanmaa", "Satakunta", "South Karelia",
    "South Ostrobothnia", "South Savo", "Southwest Finland", "Uusimaa",
  ],
  Poland: [
    "Greater Poland", "Kuyavia-Pomerania", "Lesser Poland", "Łódź", "Lower Silesia",
    "Lublin", "Lubusz", "Masovia", "Opole", "Podlaskie", "Pomerania",
    "Silesia", "Subcarpathia", "Świętokrzyskie", "Warmia-Masuria", "West Pomerania",
  ],
  Portugal: [
    "Aveiro", "Azores", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra",
    "Évora", "Faro", "Guarda", "Leiria", "Lisbon", "Madeira", "Portalegre",
    "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu",
  ],
  Belgium: [
    "Antwerp", "Brussels", "East Flanders", "Flemish Brabant", "Hainaut",
    "Liège", "Limburg", "Luxembourg", "Namur", "Walloon Brabant", "West Flanders",
  ],
  Austria: [
    "Burgenland", "Carinthia", "Lower Austria", "Salzburg", "Styria", "Tyrol",
    "Upper Austria", "Vienna", "Vorarlberg",
  ],
  Greece: [
    "Attica", "Central Greece", "Central Macedonia", "Crete", "Eastern Macedonia and Thrace",
    "Epirus", "Ionian Islands", "North Aegean", "Peloponnese", "South Aegean",
    "Thessaly", "Western Greece", "Western Macedonia",
  ],
  Ireland: ["Connacht", "Leinster", "Munster", "Ulster"],
  Turkey: [
    "Aegean", "Black Sea", "Central Anatolia", "Eastern Anatolia",
    "Marmara", "Mediterranean", "Southeastern Anatolia",
  ],
  Russia: [
    "Central", "North Caucasus", "Northwestern", "Siberian",
    "Southern", "Ural", "Volga", "Far Eastern",
  ],
  Ukraine: [
    "Cherkasy", "Chernihiv", "Chernivtsi", "Dnipropetrovsk", "Donetsk",
    "Ivano-Frankivsk", "Kharkiv", "Kherson", "Khmelnytskyi", "Kirovohrad",
    "Kyiv", "Kyiv City", "Luhansk", "Lviv", "Mykolaiv", "Odessa", "Poltava",
    "Rivne", "Sumy", "Ternopil", "Vinnytsia", "Volyn", "Zakarpattia",
    "Zaporizhzhia", "Zhytomyr",
  ],
  Romania: [
    "Alba", "Arad", "Argeș", "Bacău", "Bihor", "Bistrița-Năsăud", "Botoșani",
    "Brașov", "Brăila", "Bucharest", "Buzău", "Călărași", "Caraș-Severin",
    "Cluj", "Constanța", "Covasna", "Dâmbovița", "Dolj", "Galați", "Giurgiu",
    "Gorj", "Harghita", "Hunedoara", "Ialomița", "Iași", "Ilfov", "Maramureș",
    "Mehedinți", "Mureș", "Neamț", "Olt", "Prahova", "Sălaj", "Satu Mare",
    "Sibiu", "Suceava", "Teleorman", "Timiș", "Tulcea", "Vâlcea", "Vaslui", "Vrancea",
  ],
  Czechia: [
    "Central Bohemia", "Hradec Králové", "Karlovy Vary", "Liberec", "Moravia-Silesia",
    "Olomouc", "Pardubice", "Plzeň", "Prague", "South Bohemia", "South Moravia",
    "Ústí nad Labem", "Vysočina", "Zlín",
  ],

  // Asia
  India: [
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
    "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh",
    "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala",
    "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
    "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim",
    "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh",
    "Uttarakhand", "West Bengal",
  ],
  Japan: [
    "Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka",
    "Fukushima", "Gifu", "Gunma", "Hiroshima", "Hokkaido", "Hyogo",
    "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa",
    "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano",
    "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Osaka",
    "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi",
    "Tokushima", "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata",
    "Yamaguchi", "Yamanashi",
  ],
  China: [
    "Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong",
    "Guangxi", "Guizhou", "Hainan", "Hebei", "Heilongjiang", "Henan",
    "Hubei", "Hunan", "Inner Mongolia", "Jiangsu", "Jiangxi", "Jilin",
    "Liaoning", "Ningxia", "Qinghai", "Shaanxi", "Shandong", "Shanghai",
    "Shanxi", "Sichuan", "Tianjin", "Tibet", "Xinjiang", "Yunnan", "Zhejiang",
  ],
  "South Korea": [
    "Busan", "Chungcheongbuk", "Chungcheongnam", "Daegu", "Daejeon",
    "Gangwon", "Gwangju", "Gyeonggi", "Gyeongsangbuk", "Gyeongsangnam",
    "Incheon", "Jeju", "Jeollabuk", "Jeollanam", "Sejong", "Seoul", "Ulsan",
  ],
  Indonesia: [
    "Aceh", "Bali", "Bangka Belitung", "Banten", "Bengkulu", "Central Java",
    "Central Kalimantan", "Central Sulawesi", "East Java", "East Kalimantan",
    "East Nusa Tenggara", "Gorontalo", "Jakarta", "Jambi", "Lampung",
    "Maluku", "North Kalimantan", "North Maluku", "North Sulawesi",
    "North Sumatra", "Papua", "Riau", "Riau Islands", "South Kalimantan",
    "South Sulawesi", "South Sumatra", "Southeast Sulawesi",
    "West Java", "West Kalimantan", "West Nusa Tenggara", "West Papua",
    "West Sulawesi", "West Sumatra", "Yogyakarta",
  ],
  Philippines: [
    "Abra", "Agusan del Norte", "Agusan del Sur", "Aklan", "Albay", "Antique",
    "Apayao", "Aurora", "Basilan", "Bataan", "Batanes", "Batangas", "Benguet",
    "Biliran", "Bohol", "Bukidnon", "Bulacan", "Cagayan", "Camarines Norte",
    "Camarines Sur", "Camiguin", "Capiz", "Catanduanes", "Cavite", "Cebu",
    "Cotabato", "Davao de Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental",
    "Davao Oriental", "Dinagat Islands", "Eastern Samar", "Guimaras", "Ifugao",
    "Ilocos Norte", "Ilocos Sur", "Iloilo", "Isabela", "Kalinga", "La Union",
    "Laguna", "Lanao del Norte", "Lanao del Sur", "Leyte", "Maguindanao",
    "Marinduque", "Masbate", "Metro Manila", "Misamis Occidental", "Misamis Oriental",
    "Mountain Province", "Negros Occidental", "Negros Oriental", "Northern Samar",
    "Nueva Ecija", "Nueva Vizcaya", "Occidental Mindoro", "Oriental Mindoro",
    "Palawan", "Pampanga", "Pangasinan", "Quezon", "Quirino", "Rizal",
    "Romblon", "Samar", "Sarangani", "Siquijor", "Sorsogon", "South Cotabato",
    "Southern Leyte", "Sultan Kudarat", "Sulu", "Surigao del Norte", "Surigao del Sur",
    "Tarlac", "Tawi-Tawi", "Zambales", "Zamboanga del Norte", "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
  Vietnam: [
    "An Giang", "Bà Rịa-Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu",
    "Bắc Ninh", "Bến Tre", "Bình Dương", "Bình Định", "Bình Phước",
    "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Đà Nẵng",
    "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp",
    "Gia Lai", "Hà Giang", "Hà Nam", "Hà Nội", "Hà Tĩnh", "Hải Dương",
    "Hải Phòng", "Hậu Giang", "Hòa Bình", "Hồ Chí Minh City", "Hưng Yên",
    "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng",
    "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình",
    "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam",
    "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La",
    "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên-Huế",
    "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái",
  ],
  Thailand: [
    "Amnat Charoen", "Ang Thong", "Bangkok", "Bueng Kan", "Buri Ram",
    "Chachoengsao", "Chai Nat", "Chaiyaphum", "Chanthaburi", "Chiang Mai",
    "Chiang Rai", "Chon Buri", "Chumphon", "Kalasin", "Kamphaeng Phet",
    "Kanchanaburi", "Khon Kaen", "Krabi", "Lampang", "Lamphun", "Loei",
    "Lop Buri", "Mae Hong Son", "Maha Sarakham", "Mukdahan", "Nakhon Nayok",
    "Nakhon Pathom", "Nakhon Phanom", "Nakhon Ratchasima", "Nakhon Sawan",
    "Nakhon Si Thammarat", "Nan", "Narathiwat", "Nong Bua Lam Phu",
    "Nong Khai", "Nonthaburi", "Pathum Thani", "Pattani", "Phang Nga",
    "Phatthalung", "Phayao", "Phetchabun", "Phetchaburi", "Phichit",
    "Phitsanulok", "Phra Nakhon Si Ayutthaya", "Phrae", "Phuket",
    "Prachin Buri", "Prachuap Khiri Khan", "Ranong", "Ratchaburi",
    "Rayong", "Roi Et", "Sa Kaeo", "Sakon Nakhon", "Samut Prakan",
    "Samut Sakhon", "Samut Songkhram", "Saraburi", "Satun", "Sing Buri",
    "Sisaket", "Songkhla", "Sukhothai", "Suphan Buri", "Surat Thani",
    "Surin", "Tak", "Trang", "Trat", "Ubon Ratchathani", "Udon Thani",
    "Uthai Thani", "Uttaradit", "Yala", "Yasothon",
  ],
  Malaysia: [
    "Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan", "Malacca",
    "Negeri Sembilan", "Pahang", "Penang", "Perak", "Perlis", "Putrajaya",
    "Sabah", "Sarawak", "Selangor", "Terengganu",
  ],
  Singapore: ["Singapore"],
  "Saudi Arabia": [
    "Al Bahah", "Al Jawf", "Al Madinah", "Al Qassim", "Asir", "Eastern Province",
    "Ha'il", "Jizan", "Makkah", "Najran", "Northern Borders", "Riyadh", "Tabuk",
  ],
  "United Arab Emirates": [
    "Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras Al Khaimah", "Sharjah", "Umm Al Quwain",
  ],
  Israel: [
    "Central", "Haifa", "Jerusalem", "Northern", "Southern", "Tel Aviv",
  ],
  Qatar: ["Al Daayen", "Al Khor", "Al Rayyan", "Al Wakrah", "Al-Shahaniya", "Doha", "Madinat ash Shamal", "Umm Salal"],
  Pakistan: [
    "Azad Kashmir", "Balochistan", "Gilgit-Baltistan", "Islamabad", "Khyber Pakhtunkhwa",
    "Punjab", "Sindh",
  ],
  Bangladesh: [
    "Barisal", "Chittagong", "Dhaka", "Khulna", "Mymensingh", "Rajshahi", "Rangpur", "Sylhet",
  ],
  "Sri Lanka": [
    "Central", "Eastern", "North Central", "Northern", "North Western", "Sabaragamuwa",
    "Southern", "Uva", "Western",
  ],

  // Oceania
  Australia: [
    "Australian Capital Territory", "New South Wales", "Northern Territory",
    "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia",
  ],
  "New Zealand": [
    "Auckland", "Bay of Plenty", "Canterbury", "Chatham Islands", "Gisborne",
    "Hawke's Bay", "Manawatu-Wanganui", "Marlborough", "Nelson", "Northland",
    "Otago", "Southland", "Taranaki", "Tasman", "Waikato", "Wellington", "West Coast",
  ],
  Fiji: [
    "Ba", "Bua", "Cakaudrove", "Central", "Eastern", "Kadavu", "Lau",
    "Lomaiviti", "Macuata", "Nadroga-Navosa", "Naitasiri", "Namosi",
    "Northern", "Ra", "Rewa", "Rotuma", "Serua", "Tailevu", "Western",
  ],
  "Papua New Guinea": [
    "Bougainville", "Central", "Chimbu", "East New Britain", "East Sepik",
    "Eastern Highlands", "Enga", "Gulf", "Hela", "Jiwaka", "Madang",
    "Manus", "Milne Bay", "Morobe", "National Capital", "New Ireland",
    "Northern", "Southern Highlands", "West New Britain", "West Sepik",
    "Western", "Western Highlands",
  ],
  "Solomon Islands": [
    "Central", "Choiseul", "Guadalcanal", "Honiara", "Isabel", "Makira-Ulawa",
    "Malaita", "Rennell and Bellona", "Temotu", "Western",
  ],
}

export const COUNTRY_OPTIONS = Object.keys(COUNTRY_STATES)

export const COUNTRY_DIAL_CODES = [
  { code: "+1", label: "+1 (USA)" },
  { code: "+1", label: "+1 (CAN)" },
  { code: "+7", label: "+7 (RUS)" },
  { code: "+20", label: "+20 (EGY)" },
  { code: "+27", label: "+27 (ZAF)" },
  { code: "+30", label: "+30 (GRC)" },
  { code: "+31", label: "+31 (NLD)" },
  { code: "+32", label: "+32 (BEL)" },
  { code: "+33", label: "+33 (FRA)" },
  { code: "+34", label: "+34 (ESP)" },
  { code: "+36", label: "+36 (HUN)" },
  { code: "+39", label: "+39 (ITA)" },
  { code: "+40", label: "+40 (ROU)" },
  { code: "+41", label: "+41 (CHE)" },
  { code: "+43", label: "+43 (AUT)" },
  { code: "+44", label: "+44 (GBR)" },
  { code: "+45", label: "+45 (DNK)" },
  { code: "+46", label: "+46 (SWE)" },
  { code: "+47", label: "+47 (NOR)" },
  { code: "+48", label: "+48 (POL)" },
  { code: "+49", label: "+49 (DEU)" },
  { code: "+51", label: "+51 (PER)" },
  { code: "+52", label: "+52 (MEX)" },
  { code: "+53", label: "+53 (CUB)" },
  { code: "+54", label: "+54 (ARG)" },
  { code: "+55", label: "+55 (BRA)" },
  { code: "+56", label: "+56 (CHL)" },
  { code: "+57", label: "+57 (COL)" },
  { code: "+58", label: "+58 (VEN)" },
  { code: "+60", label: "+60 (MYS)" },
  { code: "+61", label: "+61 (AUS)" },
  { code: "+62", label: "+62 (IDN)" },
  { code: "+63", label: "+63 (PHL)" },
  { code: "+64", label: "+64 (NZL)" },
  { code: "+65", label: "+65 (SGP)" },
  { code: "+66", label: "+66 (THA)" },
  { code: "+81", label: "+81 (JPN)" },
  { code: "+82", label: "+82 (KOR)" },
  { code: "+84", label: "+84 (VNM)" },
  { code: "+86", label: "+86 (CHN)" },
  { code: "+90", label: "+90 (TUR)" },
  { code: "+91", label: "+91 (IND)" },
  { code: "+92", label: "+92 (PAK)" },
  { code: "+93", label: "+93 (AFG)" },
  { code: "+94", label: "+94 (LKA)" },
  { code: "+95", label: "+95 (MMR)" },
  { code: "+98", label: "+98 (IRN)" },
  { code: "+211", label: "+211 (SSD)" },
  { code: "+212", label: "+212 (MAR)" },
  { code: "+213", label: "+213 (DZA)" },
  { code: "+216", label: "+216 (TUN)" },
  { code: "+218", label: "+218 (LBY)" },
  { code: "+220", label: "+220 (GMB)" },
  { code: "+221", label: "+221 (SEN)" },
  { code: "+222", label: "+222 (MRT)" },
  { code: "+223", label: "+223 (MLI)" },
  { code: "+224", label: "+224 (GIN)" },
  { code: "+225", label: "+225 (CIV)" },
  { code: "+226", label: "+226 (BFA)" },
  { code: "+227", label: "+227 (NER)" },
  { code: "+228", label: "+228 (TGO)" },
  { code: "+229", label: "+229 (BEN)" },
  { code: "+230", label: "+230 (MUS)" },
  { code: "+231", label: "+231 (LBR)" },
  { code: "+232", label: "+232 (SLE)" },
  { code: "+233", label: "+233 (GHA)" },
  { code: "+234", label: "+234 (NGA)" },
  { code: "+235", label: "+235 (TCD)" },
  { code: "+236", label: "+236 (CAF)" },
  { code: "+237", label: "+237 (CMR)" },
  { code: "+238", label: "+238 (CPV)" },
  { code: "+239", label: "+239 (STP)" },
  { code: "+240", label: "+240 (GNQ)" },
  { code: "+241", label: "+241 (GAB)" },
  { code: "+242", label: "+242 (COG)" },
  { code: "+243", label: "+243 (COD)" },
  { code: "+244", label: "+244 (AGO)" },
  { code: "+245", label: "+245 (GNB)" },
  { code: "+246", label: "+246 (IOT)" },
  { code: "+248", label: "+248 (SYC)" },
  { code: "+249", label: "+249 (SDN)" },
  { code: "+250", label: "+250 (RWA)" },
  { code: "+251", label: "+251 (ETH)" },
  { code: "+252", label: "+252 (SOM)" },
  { code: "+253", label: "+253 (DJI)" },
  { code: "+254", label: "+254 (KEN)" },
  { code: "+255", label: "+255 (TZA)" },
  { code: "+256", label: "+256 (UGA)" },
  { code: "+257", label: "+257 (BDI)" },
  { code: "+258", label: "+258 (MOZ)" },
  { code: "+260", label: "+260 (ZMB)" },
  { code: "+261", label: "+261 (MDG)" },
  { code: "+262", label: "+262 (REU)" },
  { code: "+263", label: "+263 (ZWE)" },
  { code: "+264", label: "+264 (NAM)" },
  { code: "+265", label: "+265 (MWI)" },
  { code: "+266", label: "+266 (LSO)" },
  { code: "+267", label: "+267 (BWA)" },
  { code: "+268", label: "+268 (SWZ)" },
  { code: "+269", label: "+269 (COM)" },
  { code: "+290", label: "+290 (SHN)" },
  { code: "+291", label: "+291 (ERI)" },
  { code: "+297", label: "+297 (ABW)" },
  { code: "+298", label: "+298 (FRO)" },
  { code: "+299", label: "+299 (GRL)" },
  { code: "+350", label: "+350 (GIB)" },
  { code: "+351", label: "+351 (PRT)" },
  { code: "+352", label: "+352 (LUX)" },
  { code: "+353", label: "+353 (IRL)" },
  { code: "+354", label: "+354 (ISL)" },
  { code: "+355", label: "+355 (ALB)" },
  { code: "+356", label: "+356 (MLT)" },
  { code: "+357", label: "+357 (CYP)" },
  { code: "+358", label: "+358 (FIN)" },
  { code: "+359", label: "+359 (BGR)" },
  { code: "+370", label: "+370 (LTU)" },
  { code: "+371", label: "+371 (LVA)" },
  { code: "+372", label: "+372 (EST)" },
  { code: "+373", label: "+373 (MDA)" },
  { code: "+374", label: "+374 (ARM)" },
  { code: "+375", label: "+375 (BLR)" },
  { code: "+376", label: "+376 (AND)" },
  { code: "+377", label: "+377 (MCO)" },
  { code: "+378", label: "+378 (SMR)" },
  { code: "+380", label: "+380 (UKR)" },
  { code: "+381", label: "+381 (SRB)" },
  { code: "+382", label: "+382 (MNE)" },
  { code: "+383", label: "+383 (XKX)" },
  { code: "+385", label: "+385 (HRV)" },
  { code: "+386", label: "+386 (SVN)" },
  { code: "+387", label: "+387 (BIH)" },
  { code: "+389", label: "+389 (MKD)" },
  { code: "+420", label: "+420 (CZE)" },
  { code: "+421", label: "+421 (SVK)" },
  { code: "+423", label: "+423 (LIE)" },
  { code: "+500", label: "+500 (FLK)" },
  { code: "+501", label: "+501 (BLZ)" },
  { code: "+502", label: "+502 (GTM)" },
  { code: "+503", label: "+503 (SLV)" },
  { code: "+504", label: "+504 (HND)" },
  { code: "+505", label: "+505 (NIC)" },
  { code: "+506", label: "+506 (CRI)" },
  { code: "+507", label: "+507 (PAN)" },
  { code: "+508", label: "+508 (SPM)" },
  { code: "+509", label: "+509 (HTI)" },
  { code: "+590", label: "+590 (GLP)" },
  { code: "+591", label: "+591 (BOL)" },
  { code: "+592", label: "+592 (GUY)" },
  { code: "+593", label: "+593 (ECU)" },
  { code: "+594", label: "+594 (GUF)" },
  { code: "+595", label: "+595 (PRY)" },
  { code: "+596", label: "+596 (MTQ)" },
  { code: "+597", label: "+597 (SUR)" },
  { code: "+598", label: "+598 (URY)" },
  { code: "+599", label: "+599 (CUW)" },
  { code: "+670", label: "+670 (TLS)" },
  { code: "+672", label: "+672 (ATA)" },
  { code: "+673", label: "+673 (BRN)" },
  { code: "+674", label: "+674 (NRU)" },
  { code: "+675", label: "+675 (PNG)" },
  { code: "+676", label: "+676 (TON)" },
  { code: "+677", label: "+677 (SLB)" },
  { code: "+678", label: "+678 (VUT)" },
  { code: "+679", label: "+679 (FJI)" },
  { code: "+680", label: "+680 (PLW)" },
  { code: "+681", label: "+681 (WLF)" },
  { code: "+682", label: "+682 (COK)" },
  { code: "+683", label: "+683 (NIU)" },
  { code: "+685", label: "+685 (WSM)" },
  { code: "+686", label: "+686 (KIR)" },
  { code: "+687", label: "+687 (NCL)" },
  { code: "+688", label: "+688 (TUV)" },
  { code: "+689", label: "+689 (PYF)" },
  { code: "+690", label: "+690 (TKL)" },
  { code: "+691", label: "+691 (FSM)" },
  { code: "+692", label: "+692 (MHL)" },
  { code: "+850", label: "+850 (PRK)" },
  { code: "+852", label: "+852 (HKG)" },
  { code: "+853", label: "+853 (MAC)" },
  { code: "+855", label: "+855 (KHM)" },
  { code: "+856", label: "+856 (LAO)" },
  { code: "+880", label: "+880 (BGD)" },
  { code: "+886", label: "+886 (TWN)" },
  { code: "+960", label: "+960 (MDV)" },
  { code: "+961", label: "+961 (LBN)" },
  { code: "+962", label: "+962 (JOR)" },
  { code: "+963", label: "+963 (SYR)" },
  { code: "+964", label: "+964 (IRQ)" },
  { code: "+965", label: "+965 (KWT)" },
  { code: "+966", label: "+966 (SAU)" },
  { code: "+967", label: "+967 (YEM)" },
  { code: "+968", label: "+968 (OMN)" },
  { code: "+971", label: "+971 (ARE)" },
  { code: "+972", label: "+972 (ISR)" },
  { code: "+973", label: "+973 (BHR)" },
  { code: "+974", label: "+974 (QAT)" },
  { code: "+975", label: "+975 (BTN)" },
  { code: "+976", label: "+976 (MNG)" },
  { code: "+977", label: "+977 (NPL)" },
  { code: "+992", label: "+992 (TJK)" },
  { code: "+993", label: "+993 (TKM)" },
  { code: "+994", label: "+994 (AZE)" },
  { code: "+995", label: "+995 (GEO)" },
  { code: "+996", label: "+996 (KGZ)" },
  { code: "+998", label: "+998 (UZB)" },
]
