export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    GOVERNANCE: '/governance',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    RESULTS: '/results',
    ORGANIZE: '/organize',
    RECEIPT_LOOKUP: '/verify-receipt',
  },
  AUTH: {
    SIGN_IN: '/platformsignin',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verify-email',
    ACTIVATE_ACCOUNT: '/activate-account',
    SESSION_EXPIRED: '/session-expired',
    UNAUTHORIZED: '/unauthorized',
  },
  ORG_AUTH: {
    SIGN_IN: '/org/signin',
    REGISTER: '/org/register',
    FORGOT_PASSWORD: '/org/forgot-password',
    RESET_PASSWORD: '/org/reset-password',
    ACCEPT_INVITATION: '/org/invitation',
  },
  PLATFORM_AUTH: {
    TWO_FACTOR: '/platform/2fa',
    SECURITY_VERIFICATION: '/platform/verify',
    BACKUP_CODE: '/platform/backup-code',
  },
  PLATFORM: {
    DASHBOARD: '/platform',
    ORGANIZATIONS: '/platform/organizations',
    ORGANIZATION_DETAIL: (id: string) => `/platform/organizations/${id}`,
    WORKSPACE: (id: string) => `/platform/organizations/${id}/workspace`,
    USER_DETAIL: (id: string) => `/platform/users/${id}`,
    ELECTIONS: '/platform/elections',
    AUDIT: '/platform/audit',
    FOUNDER_AUDIT: '/platform/founder-audit',
    ANALYTICS: '/platform/analytics',
    BILLING: '/platform/billing',
    NOTIFICATIONS: '/platform/notifications',
    MONITORING: '/platform/monitoring',
    SECURITY: '/platform/security',
    ROLES: '/platform/roles',
    STAFF: '/platform/staff',
    SUBSCRIPTIONS: '/platform/subscriptions',
    SUPPORT: '/platform/support',
    SETTINGS: '/platform/settings',
  },
  VOTER: {
    ELECTIONS: '/elections',
    ELECTION_DETAIL: (id: string) => `/elections/${id}`,
    REGISTER: (id: string) => `/elections/${id}/register`,
    AUTH: (id: string) => `/elections/${id}/auth`,
    VOTE: (id: string) => `/elections/${id}/vote`,
    SUCCESS: (id: string) => `/elections/${id}/success`,
    RESULTS: (id: string) => `/elections/${id}/results`,
    CLOSED: (id: string) => `/elections/${id}/closed`,
    RECEIPT: (passId: string) => `/receipt/${passId}`,
    CONSOLE: (id: string) => `/elections/${id}/console`,
  },
  ORG: {
    ROOT: '/org',
    SIGN_IN: '/org/signin',
    DASHBOARD: '/org/dashboard',
    SETUP: '/org/setup',
    EVENTS: '/org/events',
    CREATE_EVENT: '/org/events/create',
    EVENT_DETAIL: (id: string) => `/org/events/${id}`,
    EDIT_EVENT: (id: string) => `/org/events/${id}/edit`,
    EVENT_RESULTS: (id: string) => `/org/events/${id}/results`,
    ROLES: '/org/roles',
    TEAM: '/org/team',
    BILLING: '/org/billing',
    WORKSPACE: '/org/workspace',
    AUDIT_LOGS: '/org/audit-logs',
    HELP: '/org/help',
    REPORTS: '/org/reports',
    ARCHIVE: '/org/archive',
    TEMPLATES: '/org/templates',
  },
} as const;

export type RouteGroup = 'PUBLIC' | 'VOTER' | 'ORG' | 'PLATFORM';
