export const ROUTES = {
  PUBLIC: {
    HOME: '/',
    ABOUT: '/about',
    CONTACT: '/contact',
    GOVERNANCE: '/governance',
    PRIVACY: '/privacy',
    TERMS: '/terms',
    RESULTS: '/results',
    ORGANIZE: '/org/register',
  },
  AUTH: {
    SIGN_IN: '/signin',
    SIGN_UP: '/signup',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    VERIFY_EMAIL: '/verify-email',
    ACTIVATE_ACCOUNT: '/activate-account',
    SESSION_EXPIRED: '/session-expired',
    UNAUTHORIZED: '/unauthorized',
  },
  ORG_AUTH: {
    SIGN_IN: '/org',
    REGISTER: '/org/register',
    FORGOT_PASSWORD: '/org/forgot-password',
    RESET_PASSWORD: '/org/reset-password',
    ACCEPT_INVITATION: '/org/invitation',
  },
  PLATFORM_AUTH: {
    TWO_FACTOR: '/platform/2fa',
    SECURITY_VERIFICATION: '/platform/verify',
    BACKUP_CODE: '/platform/backup-code',
  },
  VOTER: {
    ELECTIONS: '/elections',
    ELECTION_DETAIL: (id: string) => `/elections/${id}`,
    REGISTER: (id: string) => `/elections/${id}/register`,
    AUTH: (id: string) => `/elections/${id}/auth`,
    VOTE: (id: string) => `/elections/${id}/vote`,
    SUCCESS: (id: string) => `/elections/${id}/success`,
    RESULTS: (id: string) => `/elections/${id}/results`,
    CLOSED: (id: string) => `/elections/${id}/closed`,
    RECEIPT: (passId: string) => `/receipt/${passId}`,
  },
  ORG: {
    ROOT: '/org',
    SIGN_IN: '/org',
    DASHBOARD: '/org/dashboard',
    SETUP: '/org/setup',
    EVENTS: '/org/events',
    ELECTIONS: '/org/elections', // deprecated, use EVENTS
    CREATE_EVENT: '/org/events/create',
    EVENT_DETAIL: (id: string) => `/org/events/${id}`,
    TEAM: '/org/team',
    BILLING: '/org/billing',
    WORKSPACE: '/org/workspace',
    AUDIT_LOGS: '/org/audit-logs',
    HELP: '/org/help',
    REPORTS: '/org/reports',
    ARCHIVE: '/org/archive',
    TEMPLATES: '/org/templates',
  },
} as const;

export type RouteGroup = 'PUBLIC' | 'VOTER' | 'ORG';
